namespace: plattformsikkerhet
team: plattformsikkerhet
ingresses:
  - https://api-dings.prod-fss-pub.nais.io
env:
  - name: APPLICATION_PORT
    value: 8080
  - name: OIDC_ISSUER_NAME
    value: tokenDings
  - name: MOCK_ENABLED
    value: false
  - name: OIDC_DISCOVERY_URL
    value: "https://tokendings.prod-gcp.nais.io/.well-known/oauth-authorization-server"
  - name: OIDC_ACCEPTED_AUDIENCE
    value: prod-fss:plattformsikkerhet:api-dings
  - name: GCP_ENABLED
    value: false
replicas:
  min: 1
  max: 1
outbound-host:
  - tokendings.prod-gcp.nais.io
